[package]
name = "http-file"
version = "0.1.0"
edition = "2021"

[features]

[dependencies]
bytes = "1.3.0"
http = "0.2.8"
percent-encoding = "2.2.0"
futures-core = { version = "0.3.25", default-features = false }
pin-project-lite = "0.2.9"
tokio = { version = "1.23.0", features = ["fs", "io-util"] }

[dev-dependencies]
tokio = { version = "1.23.0", features = ["macros", "rt"] }
