[alias]
ci-check-exclude-io-uring = "hack --workspace --feature-powerset --exclude-features=io-uring check --tests --examples"
ci-check = "hack --workspace --feature-powerset check --tests --examples"

ci-test-exclude-io-uring = "hack test --workspace --feature-powerset --exclude-features=io-uring --lib --tests --no-fail-fast -- --nocapture"
ci-test = "hack test --workspace --feature-powerset --lib --tests --no-fail-fast -- --nocapture"
